on: push
name: Slack Notification
jobs:
  slackNotifications:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub
        SLACK_ICON: https://github.com/favicon.ico
        SLACK_COLOR: ${{ job.status }}
        MSG_MINIMAL: ref,commit,message